//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MyPOS.com.misaldotelcel {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ApplicationServicesBinding", Namespace="http://www.misaldotelcel.com/ws/nusoap")]
    public partial class ApplicationServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BancosWsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenBancoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenSaldoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaldoRecargasOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaldoRecargasAndroidOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReportarDepOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistroUsuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaDOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuenoOperationCompleted;
        
        private System.Threading.SendOrPostCallback VentasOperationCompleted;
        
        private System.Threading.SendOrPostCallback RUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaRFCOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaDepSOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReportarDepAndroidOperationCompleted;
        
        private System.Threading.SendOrPostCallback VentaWOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenSaldoWOperationCompleted;
        
        private System.Threading.SendOrPostCallback TraspasoWOperationCompleted;
        
        private System.Threading.SendOrPostCallback CorteWOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecargaEWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecargaEWSandroidOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecargaEWSmaquinaAOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecargaEWSjavaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecargaWOperationCompleted;
        
        private System.Threading.SendOrPostCallback PaquetesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ApplicationServices() {
            this.Url = global::MyPOS.Properties.Settings.Default.POSTiempoAireServicios_com_misaldotelcel_ApplicationServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BancosWsCompletedEventHandler BancosWsCompleted;
        
        /// <remarks/>
        public event ObtenBancoCompletedEventHandler ObtenBancoCompleted;
        
        /// <remarks/>
        public event ObtenSaldoCompletedEventHandler ObtenSaldoCompleted;
        
        /// <remarks/>
        public event SaldoRecargasCompletedEventHandler SaldoRecargasCompleted;
        
        /// <remarks/>
        public event SaldoRecargasAndroidCompletedEventHandler SaldoRecargasAndroidCompleted;
        
        /// <remarks/>
        public event ReportarDepCompletedEventHandler ReportarDepCompleted;
        
        /// <remarks/>
        public event RegistroUsuariosCompletedEventHandler RegistroUsuariosCompleted;
        
        /// <remarks/>
        public event ConsultaDCompletedEventHandler ConsultaDCompleted;
        
        /// <remarks/>
        public event BuenoCompletedEventHandler BuenoCompleted;
        
        /// <remarks/>
        public event VentasCompletedEventHandler VentasCompleted;
        
        /// <remarks/>
        public event RUsuarioCompletedEventHandler RUsuarioCompleted;
        
        /// <remarks/>
        public event ConsultaRFCCompletedEventHandler ConsultaRFCCompleted;
        
        /// <remarks/>
        public event ConsultaDepSCompletedEventHandler ConsultaDepSCompleted;
        
        /// <remarks/>
        public event ReportarDepAndroidCompletedEventHandler ReportarDepAndroidCompleted;
        
        /// <remarks/>
        public event VentaWCompletedEventHandler VentaWCompleted;
        
        /// <remarks/>
        public event ObtenSaldoWCompletedEventHandler ObtenSaldoWCompleted;
        
        /// <remarks/>
        public event TraspasoWCompletedEventHandler TraspasoWCompleted;
        
        /// <remarks/>
        public event CorteWCompletedEventHandler CorteWCompleted;
        
        /// <remarks/>
        public event RecargaEWSCompletedEventHandler RecargaEWSCompleted;
        
        /// <remarks/>
        public event RecargaEWSandroidCompletedEventHandler RecargaEWSandroidCompleted;
        
        /// <remarks/>
        public event RecargaEWSmaquinaACompletedEventHandler RecargaEWSmaquinaACompleted;
        
        /// <remarks/>
        public event RecargaEWSjavaCompletedEventHandler RecargaEWSjavaCompleted;
        
        /// <remarks/>
        public event RecargaWCompletedEventHandler RecargaWCompleted;
        
        /// <remarks/>
        public event PaquetesCompletedEventHandler PaquetesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://misaldotelcel.com/ws/index.php/BancosWs", RequestNamespace="http://www.misaldotelcel.com/ws/nusoap", ResponseNamespace="http://www.misaldotelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("return1")]
        public string BancosWs(string cadena) {
            object[] results = this.Invoke("BancosWs", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BancosWsAsync(string cadena) {
            this.BancosWsAsync(cadena, null);
        }
        
        /// <remarks/>
        public void BancosWsAsync(string cadena, object userState) {
            if ((this.BancosWsOperationCompleted == null)) {
                this.BancosWsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBancosWsOperationCompleted);
            }
            this.InvokeAsync("BancosWs", new object[] {
                        cadena}, this.BancosWsOperationCompleted, userState);
        }
        
        private void OnBancosWsOperationCompleted(object arg) {
            if ((this.BancosWsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BancosWsCompleted(this, new BancosWsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://misaldotelcel.com/ws/index.php/ObtenBanco", RequestNamespace="http://www.misaldotelcel.com/ws/nusoap", ResponseNamespace="http://www.misaldotelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("return1")]
        public string ObtenBanco(string cadena) {
            object[] results = this.Invoke("ObtenBanco", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenBancoAsync(string cadena) {
            this.ObtenBancoAsync(cadena, null);
        }
        
        /// <remarks/>
        public void ObtenBancoAsync(string cadena, object userState) {
            if ((this.ObtenBancoOperationCompleted == null)) {
                this.ObtenBancoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenBancoOperationCompleted);
            }
            this.InvokeAsync("ObtenBanco", new object[] {
                        cadena}, this.ObtenBancoOperationCompleted, userState);
        }
        
        private void OnObtenBancoOperationCompleted(object arg) {
            if ((this.ObtenBancoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenBancoCompleted(this, new ObtenBancoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://misaldotelcel.com/ws/index.php/ObtenSaldo", RequestNamespace="http://www.misaldotelcel.com/ws/nusoap", ResponseNamespace="http://www.misaldotelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("return1")]
        public string ObtenSaldo(string cadena) {
            object[] results = this.Invoke("ObtenSaldo", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenSaldoAsync(string cadena) {
            this.ObtenSaldoAsync(cadena, null);
        }
        
        /// <remarks/>
        public void ObtenSaldoAsync(string cadena, object userState) {
            if ((this.ObtenSaldoOperationCompleted == null)) {
                this.ObtenSaldoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenSaldoOperationCompleted);
            }
            this.InvokeAsync("ObtenSaldo", new object[] {
                        cadena}, this.ObtenSaldoOperationCompleted, userState);
        }
        
        private void OnObtenSaldoOperationCompleted(object arg) {
            if ((this.ObtenSaldoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenSaldoCompleted(this, new ObtenSaldoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://misaldotelcel.com/ws/index.php/SaldoRecargas", RequestNamespace="http://www.misaldotelcel.com/ws/nusoap", ResponseNamespace="http://www.misaldotelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("return1")]
        public string SaldoRecargas(string cadena) {
            object[] results = this.Invoke("SaldoRecargas", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaldoRecargasAsync(string cadena) {
            this.SaldoRecargasAsync(cadena, null);
        }
        
        /// <remarks/>
        public void SaldoRecargasAsync(string cadena, object userState) {
            if ((this.SaldoRecargasOperationCompleted == null)) {
                this.SaldoRecargasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaldoRecargasOperationCompleted);
            }
            this.InvokeAsync("SaldoRecargas", new object[] {
                        cadena}, this.SaldoRecargasOperationCompleted, userState);
        }
        
        private void OnSaldoRecargasOperationCompleted(object arg) {
            if ((this.SaldoRecargasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaldoRecargasCompleted(this, new SaldoRecargasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://misaldotelcel.com/ws/index.php/SaldoRecargasAndroid", RequestNamespace="http://www.misaldotelcel.com/ws/nusoap", ResponseNamespace="http://www.misaldotelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("return1")]
        public string SaldoRecargasAndroid(string cadena) {
            object[] results = this.Invoke("SaldoRecargasAndroid", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaldoRecargasAndroidAsync(string cadena) {
            this.SaldoRecargasAndroidAsync(cadena, null);
        }
        
        /// <remarks/>
        public void SaldoRecargasAndroidAsync(string cadena, object userState) {
            if ((this.SaldoRecargasAndroidOperationCompleted == null)) {
                this.SaldoRecargasAndroidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaldoRecargasAndroidOperationCompleted);
            }
            this.InvokeAsync("SaldoRecargasAndroid", new object[] {
                        cadena}, this.SaldoRecargasAndroidOperationCompleted, userState);
        }
        
        private void OnSaldoRecargasAndroidOperationCompleted(object arg) {
            if ((this.SaldoRecargasAndroidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaldoRecargasAndroidCompleted(this, new SaldoRecargasAndroidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://misaldotelcel.com/ws/index.php/ReportarDep", RequestNamespace="http://www.misaldotelcel.com/ws/nusoap", ResponseNamespace="http://www.misaldotelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("return1")]
        public string ReportarDep(string cadena) {
            object[] results = this.Invoke("ReportarDep", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReportarDepAsync(string cadena) {
            this.ReportarDepAsync(cadena, null);
        }
        
        /// <remarks/>
        public void ReportarDepAsync(string cadena, object userState) {
            if ((this.ReportarDepOperationCompleted == null)) {
                this.ReportarDepOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReportarDepOperationCompleted);
            }
            this.InvokeAsync("ReportarDep", new object[] {
                        cadena}, this.ReportarDepOperationCompleted, userState);
        }
        
        private void OnReportarDepOperationCompleted(object arg) {
            if ((this.ReportarDepCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReportarDepCompleted(this, new ReportarDepCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://misaldotelcel.com/ws/index.php/RegistroUsuarios", RequestNamespace="http://www.misaldotelcel.com/ws/nusoap", ResponseNamespace="http://www.misaldotelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("return1")]
        public string RegistroUsuarios(string cadena) {
            object[] results = this.Invoke("RegistroUsuarios", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RegistroUsuariosAsync(string cadena) {
            this.RegistroUsuariosAsync(cadena, null);
        }
        
        /// <remarks/>
        public void RegistroUsuariosAsync(string cadena, object userState) {
            if ((this.RegistroUsuariosOperationCompleted == null)) {
                this.RegistroUsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistroUsuariosOperationCompleted);
            }
            this.InvokeAsync("RegistroUsuarios", new object[] {
                        cadena}, this.RegistroUsuariosOperationCompleted, userState);
        }
        
        private void OnRegistroUsuariosOperationCompleted(object arg) {
            if ((this.RegistroUsuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistroUsuariosCompleted(this, new RegistroUsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://misaldotelcel.com/ws/index.php/ConsultaD", RequestNamespace="http://www.misaldotelcel.com/ws/nusoap", ResponseNamespace="http://www.misaldotelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("resultado")]
        public string ConsultaD(string cadena) {
            object[] results = this.Invoke("ConsultaD", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaDAsync(string cadena) {
            this.ConsultaDAsync(cadena, null);
        }
        
        /// <remarks/>
        public void ConsultaDAsync(string cadena, object userState) {
            if ((this.ConsultaDOperationCompleted == null)) {
                this.ConsultaDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaDOperationCompleted);
            }
            this.InvokeAsync("ConsultaD", new object[] {
                        cadena}, this.ConsultaDOperationCompleted, userState);
        }
        
        private void OnConsultaDOperationCompleted(object arg) {
            if ((this.ConsultaDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaDCompleted(this, new ConsultaDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://misaldotelcel.com/ws/index.php/Bueno", RequestNamespace="http://www.misaldotelcel.com/ws/nusoap", ResponseNamespace="http://www.misaldotelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("resultado")]
        public string Bueno(string cadena) {
            object[] results = this.Invoke("Bueno", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BuenoAsync(string cadena) {
            this.BuenoAsync(cadena, null);
        }
        
        /// <remarks/>
        public void BuenoAsync(string cadena, object userState) {
            if ((this.BuenoOperationCompleted == null)) {
                this.BuenoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuenoOperationCompleted);
            }
            this.InvokeAsync("Bueno", new object[] {
                        cadena}, this.BuenoOperationCompleted, userState);
        }
        
        private void OnBuenoOperationCompleted(object arg) {
            if ((this.BuenoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuenoCompleted(this, new BuenoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://misaldotelcel.com/ws/index.php/Ventas", RequestNamespace="http://www.misaldotelcel.com/ws/nusoap", ResponseNamespace="http://www.misaldotelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("resultado")]
        public string Ventas(string cadena) {
            object[] results = this.Invoke("Ventas", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VentasAsync(string cadena) {
            this.VentasAsync(cadena, null);
        }
        
        /// <remarks/>
        public void VentasAsync(string cadena, object userState) {
            if ((this.VentasOperationCompleted == null)) {
                this.VentasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVentasOperationCompleted);
            }
            this.InvokeAsync("Ventas", new object[] {
                        cadena}, this.VentasOperationCompleted, userState);
        }
        
        private void OnVentasOperationCompleted(object arg) {
            if ((this.VentasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VentasCompleted(this, new VentasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://misaldotelcel.com/ws/index.php/RUsuario", RequestNamespace="http://www.misaldotelcel.com/ws/nusoap", ResponseNamespace="http://www.misaldotelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("resultado")]
        public string RUsuario(string cadena) {
            object[] results = this.Invoke("RUsuario", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RUsuarioAsync(string cadena) {
            this.RUsuarioAsync(cadena, null);
        }
        
        /// <remarks/>
        public void RUsuarioAsync(string cadena, object userState) {
            if ((this.RUsuarioOperationCompleted == null)) {
                this.RUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRUsuarioOperationCompleted);
            }
            this.InvokeAsync("RUsuario", new object[] {
                        cadena}, this.RUsuarioOperationCompleted, userState);
        }
        
        private void OnRUsuarioOperationCompleted(object arg) {
            if ((this.RUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RUsuarioCompleted(this, new RUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://misaldotelcel.com/ws/index.php/ConsultaRFC", RequestNamespace="http://www.misaldotelcel.com/ws/nusoap", ResponseNamespace="http://www.misaldotelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("resultado")]
        public string ConsultaRFC(string cadena) {
            object[] results = this.Invoke("ConsultaRFC", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaRFCAsync(string cadena) {
            this.ConsultaRFCAsync(cadena, null);
        }
        
        /// <remarks/>
        public void ConsultaRFCAsync(string cadena, object userState) {
            if ((this.ConsultaRFCOperationCompleted == null)) {
                this.ConsultaRFCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaRFCOperationCompleted);
            }
            this.InvokeAsync("ConsultaRFC", new object[] {
                        cadena}, this.ConsultaRFCOperationCompleted, userState);
        }
        
        private void OnConsultaRFCOperationCompleted(object arg) {
            if ((this.ConsultaRFCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaRFCCompleted(this, new ConsultaRFCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://misaldotelcel.com/ws/index.php/ConsultaDepS", RequestNamespace="http://www.misaldotelcel.com/ws/nusoap", ResponseNamespace="http://www.misaldotelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("resultado")]
        public string ConsultaDepS(string cadena) {
            object[] results = this.Invoke("ConsultaDepS", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaDepSAsync(string cadena) {
            this.ConsultaDepSAsync(cadena, null);
        }
        
        /// <remarks/>
        public void ConsultaDepSAsync(string cadena, object userState) {
            if ((this.ConsultaDepSOperationCompleted == null)) {
                this.ConsultaDepSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaDepSOperationCompleted);
            }
            this.InvokeAsync("ConsultaDepS", new object[] {
                        cadena}, this.ConsultaDepSOperationCompleted, userState);
        }
        
        private void OnConsultaDepSOperationCompleted(object arg) {
            if ((this.ConsultaDepSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaDepSCompleted(this, new ConsultaDepSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://misaldotelcel.com/ws/index.php/ReportarDepAndroid", RequestNamespace="http://www.misaldotelcel.com/ws/nusoap", ResponseNamespace="http://www.misaldotelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("return1")]
        public string ReportarDepAndroid(string cadena) {
            object[] results = this.Invoke("ReportarDepAndroid", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReportarDepAndroidAsync(string cadena) {
            this.ReportarDepAndroidAsync(cadena, null);
        }
        
        /// <remarks/>
        public void ReportarDepAndroidAsync(string cadena, object userState) {
            if ((this.ReportarDepAndroidOperationCompleted == null)) {
                this.ReportarDepAndroidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReportarDepAndroidOperationCompleted);
            }
            this.InvokeAsync("ReportarDepAndroid", new object[] {
                        cadena}, this.ReportarDepAndroidOperationCompleted, userState);
        }
        
        private void OnReportarDepAndroidOperationCompleted(object arg) {
            if ((this.ReportarDepAndroidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReportarDepAndroidCompleted(this, new ReportarDepAndroidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://misaldotelcel.com/ws/index.php/VentaW", RequestNamespace="http://www.misaldotelcel.com/ws/nusoap", ResponseNamespace="http://www.misaldotelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("return1")]
        public string VentaW(string cadena) {
            object[] results = this.Invoke("VentaW", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VentaWAsync(string cadena) {
            this.VentaWAsync(cadena, null);
        }
        
        /// <remarks/>
        public void VentaWAsync(string cadena, object userState) {
            if ((this.VentaWOperationCompleted == null)) {
                this.VentaWOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVentaWOperationCompleted);
            }
            this.InvokeAsync("VentaW", new object[] {
                        cadena}, this.VentaWOperationCompleted, userState);
        }
        
        private void OnVentaWOperationCompleted(object arg) {
            if ((this.VentaWCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VentaWCompleted(this, new VentaWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://misaldotelcel.com/ws/index.php/ObtenSaldoW", RequestNamespace="http://www.misaldotelcel.com/ws/nusoap", ResponseNamespace="http://www.misaldotelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("return1")]
        public string ObtenSaldoW(string cadena) {
            object[] results = this.Invoke("ObtenSaldoW", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenSaldoWAsync(string cadena) {
            this.ObtenSaldoWAsync(cadena, null);
        }
        
        /// <remarks/>
        public void ObtenSaldoWAsync(string cadena, object userState) {
            if ((this.ObtenSaldoWOperationCompleted == null)) {
                this.ObtenSaldoWOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenSaldoWOperationCompleted);
            }
            this.InvokeAsync("ObtenSaldoW", new object[] {
                        cadena}, this.ObtenSaldoWOperationCompleted, userState);
        }
        
        private void OnObtenSaldoWOperationCompleted(object arg) {
            if ((this.ObtenSaldoWCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenSaldoWCompleted(this, new ObtenSaldoWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://misaldotelcel.com/ws/index.php/TraspasoW", RequestNamespace="http://www.misaldotelcel.com/ws/nusoap", ResponseNamespace="http://www.misaldotelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("return1")]
        public string TraspasoW(string cadena) {
            object[] results = this.Invoke("TraspasoW", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TraspasoWAsync(string cadena) {
            this.TraspasoWAsync(cadena, null);
        }
        
        /// <remarks/>
        public void TraspasoWAsync(string cadena, object userState) {
            if ((this.TraspasoWOperationCompleted == null)) {
                this.TraspasoWOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraspasoWOperationCompleted);
            }
            this.InvokeAsync("TraspasoW", new object[] {
                        cadena}, this.TraspasoWOperationCompleted, userState);
        }
        
        private void OnTraspasoWOperationCompleted(object arg) {
            if ((this.TraspasoWCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TraspasoWCompleted(this, new TraspasoWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://misaldotelcel.com/ws/index.php/CorteW", RequestNamespace="http://www.misaldotelcel.com/ws/nusoap", ResponseNamespace="http://www.misaldotelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("return1")]
        public string CorteW(string cadena) {
            object[] results = this.Invoke("CorteW", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CorteWAsync(string cadena) {
            this.CorteWAsync(cadena, null);
        }
        
        /// <remarks/>
        public void CorteWAsync(string cadena, object userState) {
            if ((this.CorteWOperationCompleted == null)) {
                this.CorteWOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCorteWOperationCompleted);
            }
            this.InvokeAsync("CorteW", new object[] {
                        cadena}, this.CorteWOperationCompleted, userState);
        }
        
        private void OnCorteWOperationCompleted(object arg) {
            if ((this.CorteWCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CorteWCompleted(this, new CorteWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://misaldotelcel.com/ws/index.php/RecargaEWS", RequestNamespace="http://www.misaldotelcel.com/ws/nusoap", ResponseNamespace="http://www.misaldotelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("resultado")]
        public string RecargaEWS(string cadena) {
            object[] results = this.Invoke("RecargaEWS", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecargaEWSAsync(string cadena) {
            this.RecargaEWSAsync(cadena, null);
        }
        
        /// <remarks/>
        public void RecargaEWSAsync(string cadena, object userState) {
            if ((this.RecargaEWSOperationCompleted == null)) {
                this.RecargaEWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecargaEWSOperationCompleted);
            }
            this.InvokeAsync("RecargaEWS", new object[] {
                        cadena}, this.RecargaEWSOperationCompleted, userState);
        }
        
        private void OnRecargaEWSOperationCompleted(object arg) {
            if ((this.RecargaEWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecargaEWSCompleted(this, new RecargaEWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://misaldotelcel.com/ws/index.php/RecargaEWSandroid", RequestNamespace="http://www.misaldotelcel.com/ws/nusoap", ResponseNamespace="http://www.misaldotelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("resultado")]
        public string RecargaEWSandroid(string cadena) {
            object[] results = this.Invoke("RecargaEWSandroid", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecargaEWSandroidAsync(string cadena) {
            this.RecargaEWSandroidAsync(cadena, null);
        }
        
        /// <remarks/>
        public void RecargaEWSandroidAsync(string cadena, object userState) {
            if ((this.RecargaEWSandroidOperationCompleted == null)) {
                this.RecargaEWSandroidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecargaEWSandroidOperationCompleted);
            }
            this.InvokeAsync("RecargaEWSandroid", new object[] {
                        cadena}, this.RecargaEWSandroidOperationCompleted, userState);
        }
        
        private void OnRecargaEWSandroidOperationCompleted(object arg) {
            if ((this.RecargaEWSandroidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecargaEWSandroidCompleted(this, new RecargaEWSandroidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://misaldotelcel.com/ws/index.php/RecargaEWSmaquinaA", RequestNamespace="http://www.misaldotelcel.com/ws/nusoap", ResponseNamespace="http://www.misaldotelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("resultado")]
        public string RecargaEWSmaquinaA(string cadena) {
            object[] results = this.Invoke("RecargaEWSmaquinaA", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecargaEWSmaquinaAAsync(string cadena) {
            this.RecargaEWSmaquinaAAsync(cadena, null);
        }
        
        /// <remarks/>
        public void RecargaEWSmaquinaAAsync(string cadena, object userState) {
            if ((this.RecargaEWSmaquinaAOperationCompleted == null)) {
                this.RecargaEWSmaquinaAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecargaEWSmaquinaAOperationCompleted);
            }
            this.InvokeAsync("RecargaEWSmaquinaA", new object[] {
                        cadena}, this.RecargaEWSmaquinaAOperationCompleted, userState);
        }
        
        private void OnRecargaEWSmaquinaAOperationCompleted(object arg) {
            if ((this.RecargaEWSmaquinaACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecargaEWSmaquinaACompleted(this, new RecargaEWSmaquinaACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://misaldotelcel.com/ws/index.php/RecargaEWSjava", RequestNamespace="http://www.misaldotelcel.com/ws/nusoap", ResponseNamespace="http://www.misaldotelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("resultado")]
        public string RecargaEWSjava(string cadena) {
            object[] results = this.Invoke("RecargaEWSjava", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecargaEWSjavaAsync(string cadena) {
            this.RecargaEWSjavaAsync(cadena, null);
        }
        
        /// <remarks/>
        public void RecargaEWSjavaAsync(string cadena, object userState) {
            if ((this.RecargaEWSjavaOperationCompleted == null)) {
                this.RecargaEWSjavaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecargaEWSjavaOperationCompleted);
            }
            this.InvokeAsync("RecargaEWSjava", new object[] {
                        cadena}, this.RecargaEWSjavaOperationCompleted, userState);
        }
        
        private void OnRecargaEWSjavaOperationCompleted(object arg) {
            if ((this.RecargaEWSjavaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecargaEWSjavaCompleted(this, new RecargaEWSjavaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://misaldotelcel.com/ws/index.php/RecargaW", RequestNamespace="http://www.misaldotelcel.com/ws/nusoap", ResponseNamespace="http://www.misaldotelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("return1")]
        public string RecargaW(string cadena) {
            object[] results = this.Invoke("RecargaW", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecargaWAsync(string cadena) {
            this.RecargaWAsync(cadena, null);
        }
        
        /// <remarks/>
        public void RecargaWAsync(string cadena, object userState) {
            if ((this.RecargaWOperationCompleted == null)) {
                this.RecargaWOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecargaWOperationCompleted);
            }
            this.InvokeAsync("RecargaW", new object[] {
                        cadena}, this.RecargaWOperationCompleted, userState);
        }
        
        private void OnRecargaWOperationCompleted(object arg) {
            if ((this.RecargaWCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecargaWCompleted(this, new RecargaWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://misaldotelcel.com/ws/index.php/Paquetes", RequestNamespace="http://www.misaldotelcel.com/ws/nusoap", ResponseNamespace="http://www.misaldotelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("return1")]
        public string Paquetes(string cadena) {
            object[] results = this.Invoke("Paquetes", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PaquetesAsync(string cadena) {
            this.PaquetesAsync(cadena, null);
        }
        
        /// <remarks/>
        public void PaquetesAsync(string cadena, object userState) {
            if ((this.PaquetesOperationCompleted == null)) {
                this.PaquetesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPaquetesOperationCompleted);
            }
            this.InvokeAsync("Paquetes", new object[] {
                        cadena}, this.PaquetesOperationCompleted, userState);
        }
        
        private void OnPaquetesOperationCompleted(object arg) {
            if ((this.PaquetesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PaquetesCompleted(this, new PaquetesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void BancosWsCompletedEventHandler(object sender, BancosWsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BancosWsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BancosWsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ObtenBancoCompletedEventHandler(object sender, ObtenBancoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenBancoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenBancoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ObtenSaldoCompletedEventHandler(object sender, ObtenSaldoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenSaldoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenSaldoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SaldoRecargasCompletedEventHandler(object sender, SaldoRecargasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaldoRecargasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaldoRecargasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SaldoRecargasAndroidCompletedEventHandler(object sender, SaldoRecargasAndroidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaldoRecargasAndroidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaldoRecargasAndroidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ReportarDepCompletedEventHandler(object sender, ReportarDepCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReportarDepCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReportarDepCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RegistroUsuariosCompletedEventHandler(object sender, RegistroUsuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistroUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistroUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ConsultaDCompletedEventHandler(object sender, ConsultaDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void BuenoCompletedEventHandler(object sender, BuenoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuenoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuenoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void VentasCompletedEventHandler(object sender, VentasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VentasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VentasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RUsuarioCompletedEventHandler(object sender, RUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ConsultaRFCCompletedEventHandler(object sender, ConsultaRFCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaRFCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaRFCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ConsultaDepSCompletedEventHandler(object sender, ConsultaDepSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaDepSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaDepSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ReportarDepAndroidCompletedEventHandler(object sender, ReportarDepAndroidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReportarDepAndroidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReportarDepAndroidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void VentaWCompletedEventHandler(object sender, VentaWCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VentaWCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VentaWCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ObtenSaldoWCompletedEventHandler(object sender, ObtenSaldoWCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenSaldoWCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenSaldoWCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TraspasoWCompletedEventHandler(object sender, TraspasoWCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TraspasoWCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TraspasoWCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CorteWCompletedEventHandler(object sender, CorteWCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CorteWCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CorteWCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RecargaEWSCompletedEventHandler(object sender, RecargaEWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecargaEWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecargaEWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RecargaEWSandroidCompletedEventHandler(object sender, RecargaEWSandroidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecargaEWSandroidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecargaEWSandroidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RecargaEWSmaquinaACompletedEventHandler(object sender, RecargaEWSmaquinaACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecargaEWSmaquinaACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecargaEWSmaquinaACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RecargaEWSjavaCompletedEventHandler(object sender, RecargaEWSjavaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecargaEWSjavaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecargaEWSjavaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RecargaWCompletedEventHandler(object sender, RecargaWCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecargaWCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecargaWCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void PaquetesCompletedEventHandler(object sender, PaquetesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PaquetesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PaquetesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591