//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MyPOS.TiempoAire {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ApplicationServicesBinding", Namespace="http://ventatelcel.com/ws/nusoap")]
    public partial class ApplicationServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObtenSaldoOperationCompleted;
        
        private System.Threading.SendOrPostCallback PaquetesOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecargaEWSOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificaRecargaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ApplicationServices() {
            this.Url = global::MyPOS.Properties.Settings.Default.POSTiempoAireServicios_TiempoAire_ApplicationServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObtenSaldoCompletedEventHandler ObtenSaldoCompleted;
        
        /// <remarks/>
        public event PaquetesCompletedEventHandler PaquetesCompleted;
        
        /// <remarks/>
        public event RecargaEWSCompletedEventHandler RecargaEWSCompleted;
        
        /// <remarks/>
        public event VerificaRecargaCompletedEventHandler VerificaRecargaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://www.ventatelcel.com/ws/index.php/ObtenSaldo", RequestNamespace="http://ventatelcel.com/ws/nusoap", ResponseNamespace="http://ventatelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("return1")]
        public string ObtenSaldo(string cadena) {
            object[] results = this.Invoke("ObtenSaldo", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenSaldoAsync(string cadena) {
            this.ObtenSaldoAsync(cadena, null);
        }
        
        /// <remarks/>
        public void ObtenSaldoAsync(string cadena, object userState) {
            if ((this.ObtenSaldoOperationCompleted == null)) {
                this.ObtenSaldoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenSaldoOperationCompleted);
            }
            this.InvokeAsync("ObtenSaldo", new object[] {
                        cadena}, this.ObtenSaldoOperationCompleted, userState);
        }
        
        private void OnObtenSaldoOperationCompleted(object arg) {
            if ((this.ObtenSaldoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenSaldoCompleted(this, new ObtenSaldoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://www.ventatelcel.com/ws/index.php/Paquetes", RequestNamespace="http://ventatelcel.com/ws/nusoap", ResponseNamespace="http://ventatelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("resultado")]
        public string Paquetes(string cadena) {
            object[] results = this.Invoke("Paquetes", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PaquetesAsync(string cadena) {
            this.PaquetesAsync(cadena, null);
        }
        
        /// <remarks/>
        public void PaquetesAsync(string cadena, object userState) {
            if ((this.PaquetesOperationCompleted == null)) {
                this.PaquetesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPaquetesOperationCompleted);
            }
            this.InvokeAsync("Paquetes", new object[] {
                        cadena}, this.PaquetesOperationCompleted, userState);
        }
        
        private void OnPaquetesOperationCompleted(object arg) {
            if ((this.PaquetesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PaquetesCompleted(this, new PaquetesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://www.ventatelcel.com/ws/index.php/RecargaEWS", RequestNamespace="http://ventatelcel.com/ws/nusoap", ResponseNamespace="http://ventatelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("resultado")]
        public string RecargaEWS(string cadena) {
            object[] results = this.Invoke("RecargaEWS", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecargaEWSAsync(string cadena) {
            this.RecargaEWSAsync(cadena, null);
        }
        
        /// <remarks/>
        public void RecargaEWSAsync(string cadena, object userState) {
            if ((this.RecargaEWSOperationCompleted == null)) {
                this.RecargaEWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecargaEWSOperationCompleted);
            }
            this.InvokeAsync("RecargaEWS", new object[] {
                        cadena}, this.RecargaEWSOperationCompleted, userState);
        }
        
        private void OnRecargaEWSOperationCompleted(object arg) {
            if ((this.RecargaEWSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecargaEWSCompleted(this, new RecargaEWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://www.ventatelcel.com/ws/index.php/VerificaRecarga", RequestNamespace="http://ventatelcel.com/ws/nusoap", ResponseNamespace="http://ventatelcel.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("resultado")]
        public string VerificaRecarga(string cadena) {
            object[] results = this.Invoke("VerificaRecarga", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VerificaRecargaAsync(string cadena) {
            this.VerificaRecargaAsync(cadena, null);
        }
        
        /// <remarks/>
        public void VerificaRecargaAsync(string cadena, object userState) {
            if ((this.VerificaRecargaOperationCompleted == null)) {
                this.VerificaRecargaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificaRecargaOperationCompleted);
            }
            this.InvokeAsync("VerificaRecarga", new object[] {
                        cadena}, this.VerificaRecargaOperationCompleted, userState);
        }
        
        private void OnVerificaRecargaOperationCompleted(object arg) {
            if ((this.VerificaRecargaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificaRecargaCompleted(this, new VerificaRecargaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ObtenSaldoCompletedEventHandler(object sender, ObtenSaldoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenSaldoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenSaldoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void PaquetesCompletedEventHandler(object sender, PaquetesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PaquetesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PaquetesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RecargaEWSCompletedEventHandler(object sender, RecargaEWSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecargaEWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecargaEWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void VerificaRecargaCompletedEventHandler(object sender, VerificaRecargaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificaRecargaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificaRecargaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591