//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MyPOS.PagoServicios {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ApplicationServicesBinding", Namespace="http://www.recargamarcas.com/ws/nusoap")]
    public partial class ApplicationServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SaldoServiciosOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecargaServiciosOperationCompleted;
        
        private System.Threading.SendOrPostCallback VentasServiciosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProductosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ApplicationServices() {
            this.Url = global::MyPOS.Properties.Settings.Default.POSTiempoAireServicios_PagoServicios_ApplicationServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SaldoServiciosCompletedEventHandler SaldoServiciosCompleted;
        
        /// <remarks/>
        public event RecargaServiciosCompletedEventHandler RecargaServiciosCompleted;
        
        /// <remarks/>
        public event VentasServiciosCompletedEventHandler VentasServiciosCompleted;
        
        /// <remarks/>
        public event ProductosCompletedEventHandler ProductosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.recargamarcas.com/wsServicios/index.php/SaldoServicios", RequestNamespace="http://www.recargamarcas.com/ws/nusoap", ResponseNamespace="http://www.recargamarcas.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("return1")]
        public string SaldoServicios(string cadena) {
            object[] results = this.Invoke("SaldoServicios", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaldoServiciosAsync(string cadena) {
            this.SaldoServiciosAsync(cadena, null);
        }
        
        /// <remarks/>
        public void SaldoServiciosAsync(string cadena, object userState) {
            if ((this.SaldoServiciosOperationCompleted == null)) {
                this.SaldoServiciosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaldoServiciosOperationCompleted);
            }
            this.InvokeAsync("SaldoServicios", new object[] {
                        cadena}, this.SaldoServiciosOperationCompleted, userState);
        }
        
        private void OnSaldoServiciosOperationCompleted(object arg) {
            if ((this.SaldoServiciosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaldoServiciosCompleted(this, new SaldoServiciosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.recargamarcas.com/wsServicios/index.php/RecargaServicios", RequestNamespace="http://www.recargamarcas.com/ws/nusoap", ResponseNamespace="http://www.recargamarcas.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("resultado")]
        public string RecargaServicios(string cadena) {
            object[] results = this.Invoke("RecargaServicios", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RecargaServiciosAsync(string cadena) {
            this.RecargaServiciosAsync(cadena, null);
        }
        
        /// <remarks/>
        public void RecargaServiciosAsync(string cadena, object userState) {
            if ((this.RecargaServiciosOperationCompleted == null)) {
                this.RecargaServiciosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecargaServiciosOperationCompleted);
            }
            this.InvokeAsync("RecargaServicios", new object[] {
                        cadena}, this.RecargaServiciosOperationCompleted, userState);
        }
        
        private void OnRecargaServiciosOperationCompleted(object arg) {
            if ((this.RecargaServiciosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecargaServiciosCompleted(this, new RecargaServiciosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.recargamarcas.com/wsServicios/index.php/VentasServicios", RequestNamespace="http://www.recargamarcas.com/ws/nusoap", ResponseNamespace="http://www.recargamarcas.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("resultado")]
        public string VentasServicios(string cadena) {
            object[] results = this.Invoke("VentasServicios", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VentasServiciosAsync(string cadena) {
            this.VentasServiciosAsync(cadena, null);
        }
        
        /// <remarks/>
        public void VentasServiciosAsync(string cadena, object userState) {
            if ((this.VentasServiciosOperationCompleted == null)) {
                this.VentasServiciosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVentasServiciosOperationCompleted);
            }
            this.InvokeAsync("VentasServicios", new object[] {
                        cadena}, this.VentasServiciosOperationCompleted, userState);
        }
        
        private void OnVentasServiciosOperationCompleted(object arg) {
            if ((this.VentasServiciosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VentasServiciosCompleted(this, new VentasServiciosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.recargamarcas.com/wsServicios/index.php/Productos", RequestNamespace="http://www.recargamarcas.com/ws/nusoap", ResponseNamespace="http://www.recargamarcas.com/ws/nusoap")]
        [return: System.Xml.Serialization.SoapElementAttribute("return1")]
        public string Productos(string cadena) {
            object[] results = this.Invoke("Productos", new object[] {
                        cadena});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ProductosAsync(string cadena) {
            this.ProductosAsync(cadena, null);
        }
        
        /// <remarks/>
        public void ProductosAsync(string cadena, object userState) {
            if ((this.ProductosOperationCompleted == null)) {
                this.ProductosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProductosOperationCompleted);
            }
            this.InvokeAsync("Productos", new object[] {
                        cadena}, this.ProductosOperationCompleted, userState);
        }
        
        private void OnProductosOperationCompleted(object arg) {
            if ((this.ProductosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProductosCompleted(this, new ProductosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SaldoServiciosCompletedEventHandler(object sender, SaldoServiciosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaldoServiciosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaldoServiciosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RecargaServiciosCompletedEventHandler(object sender, RecargaServiciosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecargaServiciosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecargaServiciosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void VentasServiciosCompletedEventHandler(object sender, VentasServiciosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VentasServiciosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VentasServiciosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ProductosCompletedEventHandler(object sender, ProductosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProductosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProductosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591